/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollectionsCollectionIdRouteRouteImport } from './routes/collections/$collectionId/route'
import { Route as CollectionsCollectionIdIndexRouteImport } from './routes/collections/$collectionId/index'
import { Route as CollectionsCollectionIdItemsItemIdRouteImport } from './routes/collections/$collectionId/items/$itemId'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsCollectionIdRouteRoute =
  CollectionsCollectionIdRouteRouteImport.update({
    id: '/collections/$collectionId',
    path: '/collections/$collectionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CollectionsCollectionIdIndexRoute =
  CollectionsCollectionIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CollectionsCollectionIdRouteRoute,
  } as any)
const CollectionsCollectionIdItemsItemIdRoute =
  CollectionsCollectionIdItemsItemIdRouteImport.update({
    id: '/items/$itemId',
    path: '/items/$itemId',
    getParentRoute: () => CollectionsCollectionIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/collections/$collectionId': typeof CollectionsCollectionIdRouteRouteWithChildren
  '/collections/$collectionId/': typeof CollectionsCollectionIdIndexRoute
  '/collections/$collectionId/items/$itemId': typeof CollectionsCollectionIdItemsItemIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/collections/$collectionId': typeof CollectionsCollectionIdIndexRoute
  '/collections/$collectionId/items/$itemId': typeof CollectionsCollectionIdItemsItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/collections/$collectionId': typeof CollectionsCollectionIdRouteRouteWithChildren
  '/collections/$collectionId/': typeof CollectionsCollectionIdIndexRoute
  '/collections/$collectionId/items/$itemId': typeof CollectionsCollectionIdItemsItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/search'
    | '/collections/$collectionId'
    | '/collections/$collectionId/'
    | '/collections/$collectionId/items/$itemId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/search'
    | '/collections/$collectionId'
    | '/collections/$collectionId/items/$itemId'
  id:
    | '__root__'
    | '/'
    | '/search'
    | '/collections/$collectionId'
    | '/collections/$collectionId/'
    | '/collections/$collectionId/items/$itemId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SearchRoute: typeof SearchRoute
  CollectionsCollectionIdRouteRoute: typeof CollectionsCollectionIdRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$collectionId': {
      id: '/collections/$collectionId'
      path: '/collections/$collectionId'
      fullPath: '/collections/$collectionId'
      preLoaderRoute: typeof CollectionsCollectionIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$collectionId/': {
      id: '/collections/$collectionId/'
      path: '/'
      fullPath: '/collections/$collectionId/'
      preLoaderRoute: typeof CollectionsCollectionIdIndexRouteImport
      parentRoute: typeof CollectionsCollectionIdRouteRoute
    }
    '/collections/$collectionId/items/$itemId': {
      id: '/collections/$collectionId/items/$itemId'
      path: '/items/$itemId'
      fullPath: '/collections/$collectionId/items/$itemId'
      preLoaderRoute: typeof CollectionsCollectionIdItemsItemIdRouteImport
      parentRoute: typeof CollectionsCollectionIdRouteRoute
    }
  }
}

interface CollectionsCollectionIdRouteRouteChildren {
  CollectionsCollectionIdIndexRoute: typeof CollectionsCollectionIdIndexRoute
  CollectionsCollectionIdItemsItemIdRoute: typeof CollectionsCollectionIdItemsItemIdRoute
}

const CollectionsCollectionIdRouteRouteChildren: CollectionsCollectionIdRouteRouteChildren =
  {
    CollectionsCollectionIdIndexRoute: CollectionsCollectionIdIndexRoute,
    CollectionsCollectionIdItemsItemIdRoute:
      CollectionsCollectionIdItemsItemIdRoute,
  }

const CollectionsCollectionIdRouteRouteWithChildren =
  CollectionsCollectionIdRouteRoute._addFileChildren(
    CollectionsCollectionIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SearchRoute: SearchRoute,
  CollectionsCollectionIdRouteRoute:
    CollectionsCollectionIdRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
